[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day_30 = "8viWXs1V6JE3uaw1hUnJHCRYkjx4TSZFSS1atMLVYvr3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
