[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day_31 = "GLoh9562fxifh5k9o4UAweW2RSxqDepNjHGehS9TSVTV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
