[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
initialization_insecure = "BbLHbr2L494H57b1a3yobSBedfkgnC3SHpZKHKhqT9Ez"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
