[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day_24 = "ApLXPPbSVSvEkkss2pzyKKpXFxXj6uuVN7Bsu3Y4XsBx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
