[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
change_owner = "7vavnkdV4UFNtdDWEo67Caf2eQNSjy9C6BG2QAJPuL3C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
